"""
Asynchronous molecular docking endpoints.

Endpoints:
- POST /api/dock/start
- GET /api/dock/status/{task_id}

Design:
- In-memory task registry for MVP polling architecture.
- Background task execution to avoid request timeouts.
- Optional real docking via Vina + Meeko + RDKit.
- Deterministic mock fallback when dependencies/targets are unavailable.
"""

from __future__ import annotations

import hashlib
import logging
import os
import tempfile
import threading
import time
import uuid
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Optional

from fastapi import APIRouter, BackgroundTasks, HTTPException

from schemas.docking import (
    DockStartRequest,
    DockStartResponse,
    DockStatusResponse,
)
from utils.rdkit_helper import validate_smiles

logger = logging.getLogger(__name__)
router = APIRouter()


TARGETS_DIR = Path(os.getenv("DOCKING_TARGETS_DIR", Path(__file__).resolve().parents[1] / "targets"))

MOCK_RECEPTOR_PDBQT = (
    "REMARK  Mock receptor generated by DrugForge docking MVP\n"
    "ATOM      1  C   REC A   1      15.000  22.000   9.000  0.00  0.00    +0.000 C\n"
    "ATOM      2  N   REC A   1      16.250  22.450   9.420  0.00  0.00    -0.100 NA\n"
    "ATOM      3  O   REC A   1      14.220  21.180   8.330  0.00  0.00    -0.200 OA\n"
    "ATOM      4  C   REC A   1      15.830  23.350  10.100  0.00  0.00    +0.000 C\n"
    "TER\n"
)

TARGET_CONFIG: dict[str, dict[str, Any]] = {
    "cox2": {
        "receptor": "cox2_receptor.pdbqt",
        "center": [22.1, 10.5, -14.3],
        "box_size": [20.0, 20.0, 20.0],
    },
    "ace2": {
        "receptor": "ace2_receptor.pdbqt",
        "center": [15.1, 22.5, 9.0],
        "box_size": [20.0, 20.0, 20.0],
    },
}

DOCKING_TASKS: dict[str, dict[str, Any]] = {}
DOCKING_TASKS_LOCK = threading.Lock()


def _utc_now_iso() -> str:
    return datetime.now(timezone.utc).isoformat()


def _set_task(task_id: str, **fields: Any) -> None:
    with DOCKING_TASKS_LOCK:
        task = DOCKING_TASKS.get(task_id)
        if task is None:
            return
        task.update(fields)


def _deterministic_mock_result(smiles: str, target: str) -> dict[str, Any]:
    seed_source = f"{smiles}|{target}"
    digest = hashlib.sha256(seed_source.encode("utf-8")).hexdigest()
    affinity_base = int(digest[:8], 16) / 0xFFFFFFFF
    affinity = round(-12.0 + (affinity_base * 7.0), 3)

    mock_pose = (
        "REMARK  Mock docking pose generated by DrugForge fallback mode\n"
        "REMARK  Replace with real Vina output once targets + binaries are available\n"
        "ROOT\n"
        "ATOM      1  C   LIG A   1      11.250  12.180   8.010  0.00  0.00    +0.000 C\n"
        "ATOM      2  O   LIG A   1      12.410  12.860   8.520  0.00  0.00    -0.200 OA\n"
        "ATOM      3  N   LIG A   1      10.180  11.700   7.430  0.00  0.00    -0.100 NA\n"
        "ENDROOT\n"
        "TORSDOF 0\n"
    )

    return {
        "affinity_kcal_mol": affinity,
        "docked_ligand_pdbqt": mock_pose,
        "mode": "mock",
    }


def _read_receptor_content(target: str) -> tuple[str, str, Optional[str]]:
    target_cfg = TARGET_CONFIG[target]
    receptor_name = target_cfg["receptor"]
    receptor_path = TARGETS_DIR / receptor_name

    if receptor_path.exists():
        return receptor_path.read_text(), receptor_name, "file"

    return MOCK_RECEPTOR_PDBQT, receptor_name, "mock"


def _prepare_ligand_pdbqt_from_smiles(smiles: str) -> str:
    from rdkit import Chem
    from rdkit.Chem import AllChem

    mol = Chem.MolFromSmiles(smiles)
    if mol is None:
        raise ValueError("Invalid SMILES string")

    mol = Chem.AddHs(mol)
    params = AllChem.ETKDGv3()
    params.randomSeed = 42
    embed_res = AllChem.EmbedMolecule(mol, params)
    if embed_res == -1:
        embed_res = AllChem.EmbedMolecule(mol, useRandomCoords=True)
        if embed_res == -1:
            raise ValueError("Failed to embed ligand in 3D")

    try:
        AllChem.MMFFOptimizeMolecule(mol, maxIters=300)
    except Exception:
        logger.warning("MMFF optimization skipped for docking ligand")

    from meeko import MoleculePreparation

    preparator = MoleculePreparation()
    setups = preparator.prepare(mol)
    if not setups:
        raise ValueError("Meeko failed to prepare ligand")

    pdbqt_str: Optional[str] = None

    try:
        from meeko import PDBQTWriterLegacy

        pdbqt_str, is_ok, error_msg = PDBQTWriterLegacy.write_string(setups[0])
        if not is_ok:
            raise ValueError(error_msg or "Unable to generate ligand PDBQT")
    except Exception:
        for setup in setups:
            if hasattr(setup, "write_pdbqt_string"):
                pdbqt_str = setup.write_pdbqt_string()
                break

    if not pdbqt_str:
        raise ValueError("Unable to generate ligand PDBQT from Meeko setup")

    return pdbqt_str


def _run_real_docking(smiles: str, target: str) -> dict[str, Any]:
    from vina import Vina

    target_cfg = TARGET_CONFIG[target]
    receptor_path = TARGETS_DIR / target_cfg["receptor"]
    if not receptor_path.exists():
        raise FileNotFoundError(f"Missing receptor file: {receptor_path}")

    ligand_pdbqt = _prepare_ligand_pdbqt_from_smiles(smiles)

    with tempfile.TemporaryDirectory(prefix="drugforge_dock_") as temp_dir:
        temp_path = Path(temp_dir)
        ligand_file = temp_path / "ligand.pdbqt"
        out_file = temp_path / "out.pdbqt"
        ligand_file.write_text(ligand_pdbqt)

        v = Vina(sf_name="vina")
        v.set_receptor(str(receptor_path))
        v.set_ligand_from_file(str(ligand_file))
        v.compute_vina_maps(center=target_cfg["center"], box_size=target_cfg["box_size"])

        exhaustiveness = int(os.getenv("DOCKING_EXHAUSTIVENESS", "8"))
        n_poses = int(os.getenv("DOCKING_N_POSES", "1"))
        v.dock(exhaustiveness=exhaustiveness, n_poses=n_poses)

        energies = v.energies(n_poses=1)
        affinity = float(energies[0][0]) if len(energies) > 0 else None
        v.write_poses(str(out_file), n_poses=1, overwrite=True)

        return {
            "affinity_kcal_mol": affinity,
            "docked_ligand_pdbqt": out_file.read_text(),
            "mode": "vina",
            "receptor_pdbqt": str(receptor_path.name),
        }


def _execute_docking_task(task_id: str) -> None:
    with DOCKING_TASKS_LOCK:
        task = DOCKING_TASKS.get(task_id)
        if task is None:
            return
        smiles = task["smiles"]
        target = task["target"]

    _set_task(task_id, status="processing")
    started = time.perf_counter()

    try:
        allow_real_docking = os.getenv("ENABLE_REAL_DOCKING", "false").lower() == "true"

        if allow_real_docking:
            result = _run_real_docking(smiles=smiles, target=target)
        else:
            result = _deterministic_mock_result(smiles=smiles, target=target)

        elapsed_seconds = round(time.perf_counter() - started, 3)
        _set_task(
            task_id,
            status="completed",
            affinity_kcal_mol=result.get("affinity_kcal_mol"),
            docked_ligand_pdbqt=result.get("docked_ligand_pdbqt"),
            receptor_pdbqt=result.get("receptor_pdbqt"),
            mode=result.get("mode"),
            elapsed_seconds=elapsed_seconds,
            finished_at=_utc_now_iso(),
        )
    except Exception as exc:
        logger.exception("Docking task failed for task_id=%s", task_id)
        elapsed_seconds = round(time.perf_counter() - started, 3)
        _set_task(
            task_id,
            status="failed",
            error=str(exc),
            elapsed_seconds=elapsed_seconds,
            finished_at=_utc_now_iso(),
        )


@router.post("/start", response_model=DockStartResponse)
async def start_docking(payload: DockStartRequest, background_tasks: BackgroundTasks) -> DockStartResponse:
    """
    Queue a docking task and return immediately with a task ID.
    """
    if payload.target not in TARGET_CONFIG:
        supported = ", ".join(sorted(TARGET_CONFIG.keys()))
        raise HTTPException(status_code=400, detail=f"Unsupported target '{payload.target}'. Supported: {supported}")

    try:
        validate_smiles(payload.smiles)
    except ValueError as exc:
        raise HTTPException(status_code=400, detail=str(exc))

    task_id = f"dock_{uuid.uuid4().hex[:12]}"
    created_at = _utc_now_iso()

    with DOCKING_TASKS_LOCK:
        DOCKING_TASKS[task_id] = {
            "task_id": task_id,
            "status": "queued",
            "target": payload.target,
            "smiles": payload.smiles,
            "started_at": created_at,
            "finished_at": None,
            "elapsed_seconds": None,
            "affinity_kcal_mol": None,
            "docked_ligand_pdbqt": None,
            "receptor_pdbqt": None,
            "mode": None,
            "error": None,
        }

    background_tasks.add_task(_execute_docking_task, task_id)

    return DockStartResponse(
        task_id=task_id,
        status="queued",
        target=payload.target,
        smiles=payload.smiles,
        message="Docking task queued",
    )


@router.get("/status/{task_id}", response_model=DockStatusResponse)
async def get_docking_status(task_id: str) -> DockStatusResponse:
    """
    Poll the status/result of a docking task.
    """
    with DOCKING_TASKS_LOCK:
        task: Optional[dict[str, Any]] = DOCKING_TASKS.get(task_id)

    if task is None:
        raise HTTPException(status_code=404, detail=f"Task not found: {task_id}")

    return DockStatusResponse(**task)


@router.get("/receptor/{target}")
async def get_receptor_for_target(target: str) -> dict[str, Any]:
    """
    Return receptor PDBQT content for frontend 3D overlay.
    """
    target_key = target.strip().lower()
    if target_key not in TARGET_CONFIG:
        supported = ", ".join(sorted(TARGET_CONFIG.keys()))
        raise HTTPException(status_code=400, detail=f"Unsupported target '{target_key}'. Supported: {supported}")

    receptor_pdbqt, receptor_name, source = _read_receptor_content(target_key)
    return {
        "target": target_key,
        "receptor_name": receptor_name,
        "source": source,
        "receptor_pdbqt": receptor_pdbqt,
    }
